package com.m1.s2.tmeCORBA.cache;


/**
* com/m1/s2/tmeCORBA/cache/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* mardi 31 mars 2015 12 h 16 CEST
*/

public interface FileSystemOperations 
{
  String read (String Reference);
  void write (String Reference, String Donnee);
} // interface FileSystemOperations
