package com.m1.s2.tmeCORBA.cache;


/**
* com/m1/s2/tmeCORBA/cache/FileSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* mardi 31 mars 2015 12 h 16 CEST
*/

public abstract class FileSystemPOA extends org.omg.PortableServer.Servant
 implements com.m1.s2.tmeCORBA.cache.FileSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("read", new java.lang.Integer (0));
    _methods.put ("write", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/m1/s2/tmeCORBA/cache/FileSystem/read
       {
         String Reference = in.read_wstring ();
         String $result = null;
         $result = this.read (Reference);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 1:  // com/m1/s2/tmeCORBA/cache/FileSystem/write
       {
         String Reference = in.read_wstring ();
         String Donnee = in.read_wstring ();
         this.write (Reference, Donnee);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/m1/s2/tmeCORBA/cache/FileSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileSystem _this() 
  {
    return FileSystemHelper.narrow(
    super._this_object());
  }

  public FileSystem _this(org.omg.CORBA.ORB orb) 
  {
    return FileSystemHelper.narrow(
    super._this_object(orb));
  }


} // class FileSystemPOA
