package com.m1.s2.tmeCORBA.cache;


/**
* com/m1/s2/tmeCORBA/cache/IOException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* mardi 31 mars 2015 12 h 16 CEST
*/

public final class IOException extends org.omg.CORBA.UserException
{

  public IOException ()
  {
    super(IOExceptionHelper.id());
  } // ctor


  public IOException (String $reason)
  {
    super(IOExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class IOException
