package com.m1.s2.tmeCORBA.exo2.serveur;


/**
* DividedByZeroException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mardi 24 mars 2015 12 h 27 CET
*/

public final class DividedByZeroException extends org.omg.CORBA.UserException
{

  public DividedByZeroException ()
  {
    super(DividedByZeroExceptionHelper.id());
  } // ctor


  public DividedByZeroException (String $reason)
  {
    super(DividedByZeroExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class DividedByZeroException
