package com.m1.s2.tmeCORBA.exo3;


/**
* _DistantHashTableStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mardi 24 mars 2015 12 h 40 CET
*/

public class _DistantHashTableStub extends org.omg.CORBA.portable.ObjectImpl implements DistantHashTable
{

  public boolean containsKey (String k)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("containsKey", true);
            if (k == null || k.length () > (255))
            throw new org.omg.CORBA.BAD_PARAM (0, org.omg.CORBA.CompletionStatus.COMPLETED_NO);
                com.m1.s2.tmeCORBA.exo3.DistantHashTablePackage.keyHelper.write ($out, k);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return containsKey (k        );
            } finally {
                _releaseReply ($in);
            }
  } // containsKey

  public String get (String k)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get", true);
            if (k == null || k.length () > (255))
            throw new org.omg.CORBA.BAD_PARAM (0, org.omg.CORBA.CompletionStatus.COMPLETED_NO);
                com.m1.s2.tmeCORBA.exo3.DistantHashTablePackage.keyHelper.write ($out, k);
                $in = _invoke ($out);
                String $result = com.m1.s2.tmeCORBA.exo3.DistantHashTablePackage.valueHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get (k        );
            } finally {
                _releaseReply ($in);
            }
  } // get

  public void put (String k, String val)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("put", true);
            if (k == null || k.length () > (255))
            throw new org.omg.CORBA.BAD_PARAM (0, org.omg.CORBA.CompletionStatus.COMPLETED_NO);
            if (val == null || val.length () > (888))
            throw new org.omg.CORBA.BAD_PARAM (0, org.omg.CORBA.CompletionStatus.COMPLETED_NO);
                com.m1.s2.tmeCORBA.exo3.DistantHashTablePackage.keyHelper.write ($out, k);
                com.m1.s2.tmeCORBA.exo3.DistantHashTablePackage.valueHelper.write ($out, val);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                put (k, val        );
            } finally {
                _releaseReply ($in);
            }
  } // put

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DistantHashTable:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DistantHashTableStub
