package com.m1.s2.tmeCORBA.exo3;


/**
* DistantHashTablePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mardi 24 mars 2015 12 h 40 CET
*/

public class DistantHashTablePOATie extends DistantHashTablePOA
{

  // Constructors

  public DistantHashTablePOATie ( DistantHashTableOperations delegate ) {
      this._impl = delegate;
  }
  public DistantHashTablePOATie ( DistantHashTableOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public DistantHashTableOperations _delegate() {
      return this._impl;
  }
  public void _delegate (DistantHashTableOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean containsKey (String k)
  {
    return _impl.containsKey(k);
  } // containsKey

  public String get (String k)
  {
    return _impl.get(k);
  } // get

  public void put (String k, String val)
  {
    _impl.put(k, val);
  } // put

  private DistantHashTableOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class DistantHashTablePOATie
