package com.m1.s2.tmeCORBA.exo3;


/**
* DistantHashTableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mardi 24 mars 2015 12 h 40 CET
*/

public final class DistantHashTableHolder implements org.omg.CORBA.portable.Streamable
{
  public DistantHashTable value = null;

  public DistantHashTableHolder ()
  {
  }

  public DistantHashTableHolder (DistantHashTable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistantHashTableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistantHashTableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistantHashTableHelper.type ();
  }

}
