package com.m1.s2.tmeCORBA.exo3;


/**
* DistantHashTableOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mardi 24 mars 2015 12 h 40 CET
*/

public interface DistantHashTableOperations 
{
  boolean containsKey (String k);
  String get (String k);
  void put (String k, String val);
} // interface DistantHashTableOperations
