package com.m1.s2.tmeCORBA.exo3;


/**
* DistantHashTable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mardi 24 mars 2015 12 h 40 CET
*/

public interface DistantHashTable extends DistantHashTableOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DistantHashTable
