package com.m1.s2.tmeCORBA.exo1.serveur;

/**
 * _ServeurStub.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from interface.idl mardi 24 mars 2015 12 h 27 CET
 */

public class _ServeurStub extends org.omg.CORBA.portable.ObjectImpl implements
		Serveur {

	public double add(double x, double y) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("add", true);
			$out.write_double(x);
			$out.write_double(y);
			$in = _invoke($out);
			double $result = $in.read_double();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return add(x, y);
		} finally {
			_releaseReply($in);
		}
	} // add

	public double sub(double x, double y) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("sub", true);
			$out.write_double(x);
			$out.write_double(y);
			$in = _invoke($out);
			double $result = $in.read_double();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return sub(x, y);
		} finally {
			_releaseReply($in);
		}
	} // sub

	public double mult(double x, double y) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("mult", true);
			$out.write_double(x);
			$out.write_double(y);
			$in = _invoke($out);
			double $result = $in.read_double();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return mult(x, y);
		} finally {
			_releaseReply($in);
		}
	} // mult

	public double div(double x, double y) throws DividedByZeroException {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("div", true);
			$out.write_double(x);
			$out.write_double(y);
			$in = _invoke($out);
			double $result = $in.read_double();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:DividedByZeroException:1.0"))
				throw DividedByZeroExceptionHelper.read($in);
			else
				throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return div(x, y);
		} finally {
			_releaseReply($in);
		}
	} // div

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:Serveur:1.0" };

	public String[] _ids() {
		return (String[]) __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
		try {
			org.omg.CORBA.Object obj = orb.string_to_object(str);
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
					._get_delegate();
			_set_delegate(delegate);
		} finally {
			orb.destroy();
		}
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
		try {
			String str = orb.object_to_string(this);
			s.writeUTF(str);
		} finally {
			orb.destroy();
		}
	}
} // class _ServeurStub
