package com.m1.s2.tmeCORBA.exo1.serveur;

/**
 * ServeurHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from interface.idl mardi 24 mars 2015 12 h 27 CET
 */

public final class ServeurHolder implements org.omg.CORBA.portable.Streamable {
	public Serveur value = null;

	public ServeurHolder() {
	}

	public ServeurHolder(Serveur initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = ServeurHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		ServeurHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return ServeurHelper.type();
	}

}
