package com.m1.s2.tmeCORBA.exo1.serveur;

/**
 * Serveur.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from interface.idl mardi 24 mars 2015 12 h 27 CET
 */

public interface Serveur extends ServeurOperations, org.omg.CORBA.Object,
		org.omg.CORBA.portable.IDLEntity {
} // interface Serveur
